bracketSpacing: true
endOfLine: lf
printWidth: 80
semi: false
singleQuote: false
trailingComma: all

overrides:
  - files: "*.svg"
    options:
      parser: "html"
  - files: "*.xml"
    options:
      parser: "html"
